[package]
name = "lufasu"
version = "0.1.0"
authors = ["Ash <relativistic.policeman@gmail.com>"]
edition = "2018"

[dependencies]
enum_dispatch = "0.1"
itertools = "0.8"
minifb = "0.11"
nalgebra = "0.18"
palette = "0.4"
rayon = "1.1"
rand = "0.7"
rand_distr = "0.2"